inkscape -f svg-cards.svg -i 1_club -e 1_club.png -d 90
inkscape -f svg-cards.svg -i 2_club -e 2_club.png -d 90
inkscape -f svg-cards.svg -i 3_club -e 3_club.png -d 90
inkscape -f svg-cards.svg -i 4_club -e 4_club.png -d 90
inkscape -f svg-cards.svg -i 5_club -e 5_club.png -d 90
inkscape -f svg-cards.svg -i 6_club -e 6_club.png -d 90
inkscape -f svg-cards.svg -i 7_club -e 7_club.png -d 90
inkscape -f svg-cards.svg -i 8_club -e 8_club.png -d 90
inkscape -f svg-cards.svg -i 9_club -e 9_club.png -d 90
inkscape -f svg-cards.svg -i 10_club -e 10_club.png -d 90
inkscape -f svg-cards.svg -i jack_club -e jack_club.png -d 90
inkscape -f svg-cards.svg -i queen_club -e queen_club.png -d 90
inkscape -f svg-cards.svg -i king_club -e king_club.png -d 90
inkscape -f svg-cards.svg -i 1_diamond -e 1_diamond.png -d 90
inkscape -f svg-cards.svg -i 2_diamond -e 2_diamond.png -d 90
inkscape -f svg-cards.svg -i 3_diamond -e 3_diamond.png -d 90
inkscape -f svg-cards.svg -i 4_diamond -e 4_diamond.png -d 90
inkscape -f svg-cards.svg -i 5_diamond -e 5_diamond.png -d 90
inkscape -f svg-cards.svg -i 6_diamond -e 6_diamond.png -d 90
inkscape -f svg-cards.svg -i 7_diamond -e 7_diamond.png -d 90
inkscape -f svg-cards.svg -i 8_diamond -e 8_diamond.png -d 90
inkscape -f svg-cards.svg -i 9_diamond -e 9_diamond.png -d 90
inkscape -f svg-cards.svg -i 10_diamond -e 10_diamond.png -d 90
inkscape -f svg-cards.svg -i jack_diamond -e jack_diamond.png -d 90
inkscape -f svg-cards.svg -i queen_diamond -e queen_diamond.png -d 90
inkscape -f svg-cards.svg -i king_diamond -e king_diamond.png -d 90
inkscape -f svg-cards.svg -i 1_spade -e 1_spade.png -d 90
inkscape -f svg-cards.svg -i 2_spade -e 2_spade.png -d 90
inkscape -f svg-cards.svg -i 3_spade -e 3_spade.png -d 90
inkscape -f svg-cards.svg -i 4_spade -e 4_spade.png -d 90
inkscape -f svg-cards.svg -i 5_spade -e 5_spade.png -d 90
inkscape -f svg-cards.svg -i 6_spade -e 6_spade.png -d 90
inkscape -f svg-cards.svg -i 7_spade -e 7_spade.png -d 90
inkscape -f svg-cards.svg -i 8_spade -e 8_spade.png -d 90
inkscape -f svg-cards.svg -i 9_spade -e 9_spade.png -d 90
inkscape -f svg-cards.svg -i 10_spade -e 10_spade.png -d 90
inkscape -f svg-cards.svg -i jack_spade -e jack_spade.png -d 90
inkscape -f svg-cards.svg -i queen_spade -e queen_spade.png -d 90
inkscape -f svg-cards.svg -i king_spade -e king_spade.png -d 90
inkscape -f svg-cards.svg -i 1_heart -e 1_heart.png -d 90
inkscape -f svg-cards.svg -i 2_heart -e 2_heart.png -d 90
inkscape -f svg-cards.svg -i 3_heart -e 3_heart.png -d 90
inkscape -f svg-cards.svg -i 4_heart -e 4_heart.png -d 90
inkscape -f svg-cards.svg -i 5_heart -e 5_heart.png -d 90
inkscape -f svg-cards.svg -i 6_heart -e 6_heart.png -d 90
inkscape -f svg-cards.svg -i 7_heart -e 7_heart.png -d 90
inkscape -f svg-cards.svg -i 8_heart -e 8_heart.png -d 90
inkscape -f svg-cards.svg -i 9_heart -e 9_heart.png -d 90
inkscape -f svg-cards.svg -i 10_heart -e 10_heart.png -d 90
inkscape -f svg-cards.svg -i jack_heart -e jack_heart.png -d 90
inkscape -f svg-cards.svg -i queen_heart -e queen_heart.png -d 90
inkscape -f svg-cards.svg -i king_heart -e king_heart.png -d 90
inkscape -f svg-cards.svg -i back -e back.png -d 90
